apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
      - name: airflow-scheduler
        image: apache/airflow:2.6.0  # Same version as web server
        env:
          - name: AIRFLOW__CORE__EXECUTOR
            value: "SequentialExecutor"
          - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
            value: "sqlite:////tmp/airflow.db"  # Local SQLite database
        volumeMounts:
          - name: airflow-data
            mountPath: /tmp/airflow
        command: ["bash", "-c", "airflow scheduler"]
      volumes:
      - name: airflow-data
        emptyDir: {}
