apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      initContainers:
      - name: init-airflow
        image: busybox
        command: ["sh", "-c", "mkdir -p /usr/local/airflow && chmod 777 /usr/local/airflow"]
        volumeMounts:
        - name: airflow-data
          mountPath: /usr/local/airflow
      containers:
      - name: airflow-web
        image: apache/airflow:2.6.0  # Change to your desired Airflow version
        env:
          - name: AIRFLOW__CORE__EXECUTOR
            value: "SequentialExecutor"
          - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
            value: "sqlite:////tmp/airflow.db"  # Local SQLite database
        volumeMounts:
          - name: airflow-data
            mountPath: /tmp/airflow
        command: ["bash", "-c", "airflow db init && airflow webserver"]
      volumes:
      - name: airflow-data
        emptyDir: {}
