apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow-web
          image: puckel/docker-airflow:1.10.9
          envFrom:
            - configMapRef:
                name: airflow-envvars-configmap
          volumeMounts:
            - name: logs-volume
              mountPath: /mnt/airflow/logs
            - name: requirements-volume
              mountPath: /requirements
            - name: dags-volume
              mountPath: /mnt/airflow/dags
          ports:
            - containerPort: 8080
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: test-pvc-4
        - name: requirements-volume
          configMap:
            name: requirements-configmap
        - name: dags-volume
          persistentVolumeClaim:
            claimName: test-pvc-4

