apiVersion: v1
kind: Service
metadata:
  name: airflow-web
  labeles:
    app: airflow
  namespace: default
spec:
  type: NodePort
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    app: airflow