apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
      - name: airflow-scheduler
        image: puckel/docker-airflow:1.10.9
        args: ["scheduler"]
        envFrom:
          - configMapRef:
              name: airflow-envvars-configmap
        volumeMounts:
          - name: requirements-configmap
            subPath: "requirements.txt"
            mountPath: "/requirements.txt"        
      volumes:
      - name: requirements-configmap
        configMap:
          name: requirements-configmap    


