apiVersion: v1
kind: Service
metadata:
  name: airflow-postgresql
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
  selector:
    app: airflow-postgresql