apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
        - name: scheduler
          image: puckel/docker-airflow:1.10.9
          command: ["airflow", "scheduler"]
          envFrom:
            - configMapRef:
                name: airflow-envvars-configmap
          ports:
            - containerPort: 8793  # Optional, used for communication
