apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
        - name: airflow-scheduler
          image: puckel/docker-airflow:1.10.9
          command: ["airflow", "scheduler"]
          envFrom:
            - configMapRef:
                name: airflow-envvars-configmap
          volumeMounts:
#            - name: logs-volume
#              mountPath: /mnt/airflow/logs
            - name: requirements-volume
              mountPath: /requirements
            - name: dags-host-volume
              mountPath: /mnt/airflow/dags
          ports:
            - containerPort: 8793
      volumes:
#        - name: logs-volume
#          persistentVolumeClaim:
#            claimName: airflow-logs-pvc
        - name: requirements-volume
          configMap:
            name: requirements-configmap
        - name: dags-host-volume
          hostPath:
            path: /mnt/airflow/dags
            type: Directory

