apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
  namespace: default
  labels:
    app: airflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi