apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret-3
  namespace: default
type: Opaque
data:
  azurestorageaccountname: cHZjc2hhcmU=
  azurestorageaccountkey: VDZLTHFpRC85S2JUcmk1S3pGWHlxNnBXSzVJRXpsNXRXcVlYcmtOKzdEZDBjKzMzU0hyNzhTUnJnUHNuVEsvellyT2RyTlJ0amVRQitBU3Q0aVFBb2c9PQ==