apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefilenginx
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: azurefile
  resources:
    requests:
      storage: 5Gi