apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airflow-spark-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: dns-whole-teal-bhoxdzdm.hcp.northeurope.azmk8s.io
    http:
      paths:
      - path: /spark
        pathType: Prefix
        backend:
          service:
            name: spark-master
            port:
              number: 8080
