apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Azure Disks support single pod access in ReadWriteOnce mode
  resources:
    requests:
      storage: 1Gi  # Adjust the storage size as per your requirement
  storageClassName: managed