apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master-deployment
  namespace: default  # Change if you are using a different namespace
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark
        image: bitnami/spark:latest
        ports:
        - containerPort: 8080  # Spark default port
        env:
        - name: SPARK_MODE
          value: "master"  # or "worker" depending on the role of the container
        - name: SPARK_MASTER_URL
          value: "spark://spark-master:7077"  # Adjust as needed