apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
      - name: airflow-scheduler
        image: apache/airflow:2.6.0
        env:
          - name: AIRFLOW__CORE__EXECUTOR
            value: "KubernetesExecutor"
          - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
            value: "postgresql+psycopg2://airflow:your_password@airflow-postgres:5432/airflow_db"
        command: ["bash", "-c", "airflow scheduler"]
