apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      securityContext:
        fsGroup: 1000  # Group ID that has access to the volume
      containers:
      - name: airflow-scheduler
        image: apache/airflow:2.6.0
        env:
          - name: AIRFLOW__CORE__EXECUTOR
            value: "KubernetesExecutor"
          - name: AIRFLOW__WEBSERVER__URL
            value: "http://airflow-webserver:8080" 
          - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
            value: "postgresql+psycopg2://airflow:your_password@airflow-postgres:5432/airflow_db"
          - name: AIRFLOW__KUBERNETES__LOGS_VOLUME_HOST
            value: "/mnt/azure-disk/logs"
          - name: AIRFLOW__KUBERNETES__DAGS_VOLUME_HOST
            value: "/mnt/azure-disk/dags"
  
        command: ["bash", "-c", "airflow scheduler"]
        volumeMounts:
          - name: azure-disk
            mountPath: /mnt/azure-disk
          - name: azure-file
            mountPath: /mnt/azure-file
            readOnly: false
      volumes:
      - name: azure-disk
        persistentVolumeClaim:
          claimName: airflow-scheduler-pvc1
      - name: azure-file
        persistentVolumeClaim:
          claimName: my-azurefile       
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-scheduler-pvc1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed
  resources:
    requests:
      storage: 1Gi
