apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      securityContext:
        fsGroup: 1000  # Group ID that has access to the volume
      containers:
      - name: airflow-scheduler
        image: apache/airflow:2.6.0
        env:
          - name: AIRFLOW__CORE__EXECUTOR
            value: "KubernetesExecutor"
          - name: AIRFLOW__WEBSERVER__URL
            value: "http://airflow-webserver:8080" 
          - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
            value: "postgresql+psycopg2://airflow:your_password@airflow-postgres:5432/airflow_db"
          - name: AIRFLOW__KUBERNETES__LOGS_VOLUME_HOST
            value: "/mnt/azure-file/logs"
          - name: AIRFLOW__CORE__DAGS_FOLDER
            value: "/mnt/azure-file/dags"
          - name: AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY 
            value: "okrx/airflow-custom-kubectl:latest"
          - name: AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG
            value: "2.6.0"
          - name: AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM
            value: "my-azurefile"
          - name: AIRFLOW__KUBERNETES__DAGS_VOLUME_MOUNT_PATH
            value: "/mnt/azure-file"
          - name: AIRFLOW__KUBERNETES__WORKER_DAGS_FOLDER
            value: "/mnt/azure-file/dags"
          - name: AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH
            value: "dags/"
          - name: AIRFLOW__KUBERNETES__DAGS_IN_IMAGE
            value: "False"
          - name: AIRFLOW__KUBERNETES__POD_TEMPLATE_FILE
            value: /opt/airflow/pod_template.yaml
          - name: AIRFLOW__KUBERNETES__WORKER_ENV_VARS__AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
            value: "postgresql+psycopg2://airflow:your_password@airflow-postgres:5432/airflow_db"
 
  
        command: ["bash", "-c", "airflow scheduler"]
        volumeMounts:
          - name: azure-disk
            mountPath: /mnt/azure-disk
          - name: azure-file
            mountPath: /mnt/azure-file
            readOnly: false
          - name: pod-template-volume
            mountPath: /opt/airflow/pod_template.yaml
            subPath: pod_template.yaml                  
      volumes:
      - name: azure-disk
        persistentVolumeClaim:
          claimName: airflow-scheduler-pvc1
      - name: azure-file
        persistentVolumeClaim:
          claimName: my-azurefile
      - name: pod-template-volume
        configMap:
          name: pod-template-configmap


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-scheduler-pvc1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed
  resources:
    requests:
      storage: 1Gi
