apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-template-configmap
data:
  pod_template.yaml: |
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        app: airflow-worker
    spec:
      containers:
        - name: airflow-worker
          image: apache/airflow:2.6.0
          env:
            - name: AIRFLOW__CORE__DAGS_FOLDER
              value: /mnt/azure-file/dags
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: "postgresql+psycopg2://airflow:your_password@airflow-postgres:5432/airflow_db"
          volumeMounts:
            - name: azure-file
              mountPath: /mnt/azure-file
      volumes:
        - name: azure-file
          persistentVolumeClaim:
            claimName: my-azurefile
