apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      securityContext:
        fsGroup: 1000  # Group ID that has access to the volume
      containers:
      - name: airflow-webserver
        #image: okrx/airflow-custom-kubectl:v1.3
        image: okrx/airflow-custom-kubectl:v1.4
        env:
          - name: AIRFLOW__CORE__EXECUTOR
            value: "KubernetesExecutor" 
          - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
            value: "postgresql+psycopg2://airflow:your_password@airflow-postgres:5432/airflow_db"
          - name: AIRFLOW__KUBERNETES__LOGS_VOLUME_HOST
            value: "/mnt/azure-file/logs"
          - name: AIRFLOW__CORE__DAGS_FOLDER
            value: "/mnt/azure-file/dags"
          - name: AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY 
            value: "okrx/airflow-custom-kubectl"
          - name: AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG
            value: "v1.4"
          - name: AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM
            value: "my-azurefile"
          - name: AIRFLOW__KUBERNETES__DAGS_VOLUME_MOUNT_PATH
            value: "/mnt/azure-file"  
          - name: AIRFLOW__KUBERNETES__WORKER_DAGS_FOLDER
            value: "/mnt/azure-file/dags"
          - name: AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH
            value: "dags/"
          - name: AIRFLOW__KUBERNETES__DAGS_IN_IMAGE
            value: "False" 
          - name: AIRFLOW__KUBERNETES__POD_TEMPLATE_FILE
            value: /opt/airflow/pod_template.yaml
          - name: AIRFLOW__KUBERNETES__WORKER_ENV_VARS__AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
            value: "postgresql+psycopg2://airflow:your_password@airflow-postgres:5432/airflow_db"
            

        command: ["bash", "-c", "airflow db init && airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin && airflow webserver"]
        volumeMounts:
          - name: azure-disk
            mountPath: /mnt/azure-disk
          - name: azure-file
            mountPath: /mnt/azure-file
            readOnly: false
          - name: pod-template-volume
            mountPath: /opt/airflow/pod_template.yaml
            subPath: pod_template.yaml  
      volumes:
      - name: azure-disk
        persistentVolumeClaim:
          claimName: airflow-webserver-pvc
      - name: azure-file
        persistentVolumeClaim:
          claimName: my-azurefile
      - name: pod-template-volume
        configMap:
          name: pod-template-configmap

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-webserver-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
spec:
  type: ClusterIP  # Change to LoadBalancer if you want external access
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: airflow-webserver