apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-init-2
spec:
  template:
    spec:
      containers:
      - name: airflow-init
        image: apache/airflow:2.6.0
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: "KubernetesExecutor"
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:your_password@airflow-postgres:5432/airflow_db"
        command: ["airflow", "db", "init"]
      restartPolicy: Never
  backoffLimit: 4
