apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-postgres
  template:
    metadata:
      labels:
        app: airflow-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13  # Use your desired version
        env:
          - name: POSTGRES_USER
            value: "airflow"
          - name: POSTGRES_PASSWORD
            value: "your_password"  # Clear text password
          - name: POSTGRES_DB
            value: "airflow_db"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-postgres
spec:
  ports:
  - port: 5432
  selector:
    app: airflow-postgres
