###################################
# Airflow - Common Configs
###################################
airflow:
  image:
    repository: apache/airflow
    tag: 2.6.0  # Updated to the version you are using
    pullPolicy: IfNotPresent
  executor: KubernetesExecutor  # Changed to KubernetesExecutor
  fernetKey: "7T512UXSSmBOkpWimFHIVb8jK6lfmSAvx4mO6Arehnc="
  config:
    AIRFLOW__TRIGGERER__DEFAULT_CAPACITY: 10  # Default value added
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow_db"
  podAnnotations: {}
  extraEnv:
    - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
      value: "postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow_db"  # Adjusted for your DB credentials
  extraVolumeMounts: []
  extraVolumes: []

###################################
# Airflow - Scheduler Configs
###################################
scheduler:
  resources: {}
  safeToEvict: true
  podDisruptionBudget:
    enabled: true
    maxUnavailable: "100%"
  livenessProbe:
    enabled: true
    initialDelaySeconds: 300
    periodSeconds: 30

###################################
# Airflow - WebUI Configs
###################################
web:
  replicas: 1
  baseUrl: "http://airflow-web:8080"  # Updated for internal access
  livenessProbe:
    enabled: true
    initialDelaySeconds: 300
    periodSeconds: 30

###################################
# Airflow - Worker Configs
###################################
workers:
  enabled: true
  replicas: 2  # Adjust as needed for scaling
  autoscaling:
    enabled: false

###################################
# Airflow - Logs Configs
###################################
logs:
  path: /opt/airflow/logs
  persistence:
    enabled: true  # Enabled for log persistence

###################################
# Airflow - DAGs Configs
###################################
dags:
  path: /opt/airflow/dags
  persistence:
    enabled: true  # Enable persistence for DAGs
    existingClaim: ""  # Use if you have an existing PVC
    size: 1Gi

###################################
# Kubernetes - RBAC
###################################
rbac:
  create: true

###################################
# Database - PostgreSQL Chart
###################################
postgresql:
  enabled: true
  postgresqlDatabase: airflow
  postgresqlUsername: airflow  # Adjusted to match the connection string
  postgresqlPassword: airflow  # Keep this consistent with your connection
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 8Gi

###################################
# Database - Redis Chart
###################################
redis:
  enabled: false
  password: airflow  # Keep consistent with the connection string
